In [1]:
import matplotlib.pyplot as plt 
import numpy as np
import seaborn as sns
import pandas as pd

In [3]:
df=pd.read_csv('final_df.csv')

In [10]:
def print_score(actual,prediction):
    cm=confusion_matrix(actual,prediction)
    tp=cm[1,1]
    tn=cm[0,0]
    fp=cm[0,1]
    fn=cm[1,0]
    print("Overall Accuracy : ",(tp+tn)/(tp+tn+fp+fn))
    print("Precision : ",(tp)/(tp+fp))
    print("Recall or TPR or Sensitivity: ",(tp)/(tp+fn))
    print("Specificity or TNR: ",(tn)/(tn+fp))
    

In [11]:
X=df.drop(columns='LoanStatus',axis=1)
Y=df['LoanStatus']
X=pd.get_dummies(X)
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
X_train,X_test,Y_train,Y_test=train_test_split(X,Y)

## Decision Tree

In [15]:
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier(max_depth=5,criterion='entropy')
model.fit(X_train,Y_train)
print(model.score(X_train,Y_train))
Y_pred= model.predict(X_test)
print(confusion_matrix(Y_test,Y_pred))
print(print_score(Y_test,Y_pred))
from sklearn.tree import export_text
tree_rules= export_text(model,feature_names=list(X_train))
print(tree_rules)

0.8543478260869565
[[19 33]
 [ 8 94]]
Overall Accuracy :  0.7337662337662337
Precision :  0.7401574803149606
Recall or TPR or Sensitivity:  0.9215686274509803
Specificity or TNR:  0.36538461538461536
None
|--- CreditHistory <= 0.50
|   |--- Income_Log <= 8.51
|   |   |--- class: 0
|   |--- Income_Log >  8.51
|   |   |--- LoanAmount_Log <= 4.57
|   |   |   |--- class: 1
|   |   |--- LoanAmount_Log >  4.57
|   |   |   |--- PropertyArea_Semiurban <= 0.50
|   |   |   |   |--- class: 0
|   |   |   |--- PropertyArea_Semiurban >  0.50
|   |   |   |   |--- LoanAmount_Log <= 5.13
|   |   |   |   |   |--- class: 1
|   |   |   |   |--- LoanAmount_Log >  5.13
|   |   |   |   |   |--- class: 0
|--- CreditHistory >  0.50
|   |--- PropertyArea_Semiurban <= 0.50
|   |   |--- Income_Log <= 7.78
|   |   |   |--- Gender_Female <= 0.50
|   |   |   |   |--- class: 0
|   |   |   |--- Gender_Female >  0.50
|   |   |   |   |--- Income_Log <= 7.74
|   |   |   |   |   |--- class: 1
|   |   |   |   |--- Income_L

In [16]:
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier(max_depth=10,criterion='entropy')
model.fit(X_train,Y_train)
print(model.score(X_train,Y_train))
Y_pred= model.predict(X_test)
print(confusion_matrix(Y_test,Y_pred))
print(print_score(Y_test,Y_pred))
from sklearn.tree import export_text
tree_rules= export_text(model,feature_names=list(X_train))
print(tree_rules)

0.908695652173913
[[25 27]
 [11 91]]
Overall Accuracy :  0.7532467532467533
Precision :  0.7711864406779662
Recall or TPR or Sensitivity:  0.8921568627450981
Specificity or TNR:  0.4807692307692308
None
|--- CreditHistory <= 0.50
|   |--- Income_Log <= 8.51
|   |   |--- class: 0
|   |--- Income_Log >  8.51
|   |   |--- LoanAmount_Log <= 4.57
|   |   |   |--- class: 1
|   |   |--- LoanAmount_Log >  4.57
|   |   |   |--- PropertyArea_Semiurban <= 0.50
|   |   |   |   |--- class: 0
|   |   |   |--- PropertyArea_Semiurban >  0.50
|   |   |   |   |--- LoanAmount_Log <= 5.13
|   |   |   |   |   |--- Income_Log <= 8.66
|   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |--- Income_Log >  8.66
|   |   |   |   |   |   |--- class: 1
|   |   |   |   |--- LoanAmount_Log >  5.13
|   |   |   |   |   |--- class: 0
|--- CreditHistory >  0.50
|   |--- PropertyArea_Semiurban <= 0.50
|   |   |--- Income_Log <= 7.78
|   |   |   |--- Gender_Male <= 0.50
|   |   |   |   |--- LoanAmount_Log <= 4.01
| 

## Random Forest

In [17]:
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(n_estimators=10)
model.fit(X_train,Y_train)
print(model.score(X_train,Y_train))
Y_pred= model.predict(X_test)
print(confusion_matrix(Y_test,Y_pred))
print(print_score(Y_test,Y_pred))


0.9891304347826086
[[27 25]
 [16 86]]
Overall Accuracy :  0.7337662337662337
Precision :  0.7747747747747747
Recall or TPR or Sensitivity:  0.8431372549019608
Specificity or TNR:  0.5192307692307693
None


## Knn

In [19]:
from sklearn.neighbors import KNeighborsClassifier
model=KNeighborsClassifier(n_neighbors=5)
model.fit(X_train,Y_train)
print(model.score(X_train,Y_train))
Y_pred= model.predict(X_test)
print(confusion_matrix(Y_test,Y_pred))
print(print_score(Y_test,Y_pred))

0.8130434782608695
[[12 40]
 [ 7 95]]
Overall Accuracy :  0.6948051948051948
Precision :  0.7037037037037037
Recall or TPR or Sensitivity:  0.9313725490196079
Specificity or TNR:  0.23076923076923078
None


## Naive bayes

In [20]:
from sklearn.naive_bayes import GaussianNB
model=GaussianNB()
model.fit(X_train,Y_train)
print(model.score(X_train,Y_train))
Y_pred= model.predict(X_test)
print(confusion_matrix(Y_test,Y_pred))
print(print_score(Y_test,Y_pred))

0.8260869565217391
[[21 31]
 [ 9 93]]
Overall Accuracy :  0.7402597402597403
Precision :  0.75
Recall or TPR or Sensitivity:  0.9117647058823529
Specificity or TNR:  0.40384615384615385
None


## SVM

In [21]:
from sklearn.svm import SVC
model=SVC()
model.fit(X_train,Y_train)
print(model.score(X_train,Y_train))
Y_pred= model.predict(X_test)
print(confusion_matrix(Y_test,Y_pred))
print(print_score(Y_test,Y_pred))

0.6956521739130435
[[  0  52]
 [  0 102]]
Overall Accuracy :  0.6623376623376623
Precision :  0.6623376623376623
Recall or TPR or Sensitivity:  1.0
Specificity or TNR:  0.0
None
